export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANIES_REQUEST = 'FIRST_COMPANY';
export const COMPANY_SELECTOR = 'COMPANY_SELECTOR';
export const LOAD_COMPANY_REQUEST = 'LOAD_COMPANY_REQUEST';
export const LOAD_COMPANIES_DATA = 'LOAD_COMPANIES_DATA';
export const SHOW_POPUP = 'SHOW_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';
